name: Runner Performance Profile
on: workflow_dispatch

jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Storage Profile
        run: |
          echo "### DISK USAGE PROFILE"
          sudo df -h
          sudo du -xm / --max-depth=4 2>/dev/null | awk '$1 >= 100' | sort -rn
          
          echo -e "\n### TOP 10 LARGEST FILES"
          sudo find / -type f -exec du -h {} + 2>/dev/null | sort -rh | head -n 10

      - name: Memory & CPU Profile
        run: |
          echo "### RAM USAGE"
          free -h
          
          echo -e "\n### TOP 5 PROCESSES BY MEMORY"
          ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -n 6
          
          echo -e "\n### TOP 5 PROCESSES BY CPU"
          ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -n 6

      - name: System Overhead Summary
        run: |
          echo "### RUNNER INFO"
          nproc --all | xargs echo "CPU Cores:"
          grep MemTotal /proc/meminfo | awk '{print "Total RAM: " $2/1024 " MB"}'
          uptime -p
          

      
      - name: Run fastfetch
        run: |
          sudo add-apt-repository ppa:zhangsongcui3371/fastfetch
          sudo apt update && sudo apt install fastfetch
          fastfetch
